# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "143763f6f49cac5e4da35403e12244f8"
name = "one-tick-upsell-v1"
handle = "one-tick-upsell-v1"
application_url = "https://deutschland-audi-approximately-frankfurt.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-2c4b5a7b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://deutschland-audi-approximately-frankfurt.trycloudflare.com/auth/callback",
  "https://deutschland-audi-approximately-frankfurt.trycloudflare.com/auth/shopify/callback",
  "https://deutschland-audi-approximately-frankfurt.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
