# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1fb6ca005d2def6100737b25cde309ac"
name = "one-tick-upsell-v2"
handle = "one-tick-upsell-v2"
application_url = "https://lid-theater-rose-tft.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-2c4b5a7b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://lid-theater-rose-tft.trycloudflare.com/auth/callback",
  "https://lid-theater-rose-tft.trycloudflare.com/auth/shopify/callback",
  "https://lid-theater-rose-tft.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
